/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/festival/Christmas/ch2025': RouteRecordInfo<
      '/festival/Christmas/ch2025',
      '/festival/Christmas/ch2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/festival/DoubleEleven/de2025': RouteRecordInfo<
      '/festival/DoubleEleven/de2025',
      '/festival/DoubleEleven/de2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/2025_game': RouteRecordInfo<
      '/posts/2025/2025_game',
      '/posts/2025/2025_game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/about_recently_1': RouteRecordInfo<
      '/posts/2025/about_recently_1',
      '/posts/2025/about_recently_1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/Json序列化的实现': RouteRecordInfo<
      '/posts/2025/Json序列化的实现',
      '/posts/2025/Json序列化的实现',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/markdown_editor_design': RouteRecordInfo<
      '/posts/2025/markdown_editor_design',
      '/posts/2025/markdown_editor_design',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/ms_word_preium': RouteRecordInfo<
      '/posts/2025/ms_word_preium',
      '/posts/2025/ms_word_preium',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/qt_and_webview': RouteRecordInfo<
      '/posts/2025/qt_and_webview',
      '/posts/2025/qt_and_webview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/Unity游戏CodeRegistration和MetadataRegistration的获取': RouteRecordInfo<
      '/posts/2025/Unity游戏CodeRegistration和MetadataRegistration的获取',
      '/posts/2025/Unity游戏CodeRegistration和MetadataRegistration的获取',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/从零开始学QtQuick_1': RouteRecordInfo<
      '/posts/2025/从零开始学QtQuick_1',
      '/posts/2025/从零开始学QtQuick_1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/基于DCTF-CNN的射频指纹识别': RouteRecordInfo<
      '/posts/2025/基于DCTF-CNN的射频指纹识别',
      '/posts/2025/基于DCTF-CNN的射频指纹识别',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/festival/Christmas/ch2025.md': {
      routes:
        | '/festival/Christmas/ch2025'
      views:
        | never
    }
    'pages/festival/DoubleEleven/de2025.md': {
      routes:
        | '/festival/DoubleEleven/de2025'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/2025/2025_game.md': {
      routes:
        | '/posts/2025/2025_game'
      views:
        | never
    }
    'pages/posts/2025/about_recently_1.md': {
      routes:
        | '/posts/2025/about_recently_1'
      views:
        | never
    }
    'pages/posts/2025/Json序列化的实现.md': {
      routes:
        | '/posts/2025/Json序列化的实现'
      views:
        | never
    }
    'pages/posts/2025/markdown_editor_design.md': {
      routes:
        | '/posts/2025/markdown_editor_design'
      views:
        | never
    }
    'pages/posts/2025/ms_word_preium.md': {
      routes:
        | '/posts/2025/ms_word_preium'
      views:
        | never
    }
    'pages/posts/2025/qt_and_webview.md': {
      routes:
        | '/posts/2025/qt_and_webview'
      views:
        | never
    }
    'pages/posts/2025/Unity游戏CodeRegistration和MetadataRegistration的获取.md': {
      routes:
        | '/posts/2025/Unity游戏CodeRegistration和MetadataRegistration的获取'
      views:
        | never
    }
    'pages/posts/2025/从零开始学QtQuick_1.md': {
      routes:
        | '/posts/2025/从零开始学QtQuick_1'
      views:
        | never
    }
    'pages/posts/2025/基于DCTF-CNN的射频指纹识别.md': {
      routes:
        | '/posts/2025/基于DCTF-CNN的射频指纹识别'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
